Error out if can't find spark binary

diff --git a/bin/adam-pyspark b/bin/adam-pyspark
--- a/bin/adam-pyspark
+++ b/bin/adam-pyspark
@@ -33,6 +33,10 @@ if [ -z "$SPARK_HOME" ]; then
 else
   PYSPARK="$SPARK_HOME"/bin/pyspark
 fi
+if [ -z "$PYSPARK" ]; then
+  echo "SPARK_HOME not set and pyspark not on PATH; Aborting."
+  exit 1
+fi
 echo "Using PYSPARK=$PYSPARK"
 
 # submit the job to Spark
diff --git a/bin/adam-shell b/bin/adam-shell
--- a/bin/adam-shell
+++ b/bin/adam-shell
@@ -30,6 +30,10 @@ if [ -z "$SPARK_HOME" ]; then
 else
   SPARK_SHELL="$SPARK_HOME"/bin/spark-shell
 fi
+if [ -z "$SPARK_SHELL" ]; then
+  echo "SPARK_HOME not set and spark-shell not on PATH; Aborting."
+  exit 1
+fi
 echo "Using SPARK_SHELL=$SPARK_SHELL"
 
 # submit the job to Spark
diff --git a/bin/adam-submit b/bin/adam-submit
--- a/bin/adam-submit
+++ b/bin/adam-submit
@@ -84,6 +84,10 @@ if [ -z "$SPARK_HOME" ]; then
 else
   SPARK_SUBMIT="$SPARK_HOME"/bin/spark-submit
 fi
+if [ -z "$SPARK_SUBMIT" ]; then
+  echo "SPARK_HOME not set and spark-submit not on PATH; Aborting."
+  exit 1
+fi
 echo "Using SPARK_SUBMIT=$SPARK_SUBMIT"
 
 # submit the job to Spark
